In [52]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [ ]:
import os
os.system("~/drakenew/drake-distro/build/bin/ddConsoleApp simulator.py")

In [48]:
from car import CarPlant
Car = CarPlant()
print Car.state
print Car.simulate()

[ 0.  0.  0.]
Finished simulation: [[  0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  3.99999936e-01   1.66659443e-04   1.24973963e-03]
 [  7.99998002e-01   1.33267818e-03   4.99583478e-03]
 [  1.19998485e+00   4.49491333e-03   1.12289222e-02]
 [  1.59993631e+00   1.06450642e-02   1.99334223e-02]
 [  1.99980615e+00   2.07669024e-02   3.10875785e-02]
 [  2.39951923e+00   3.58332385e-02   4.46635112e-02]
 [  2.79896495e+00   5.68025939e-02   6.06272874e-02]
 [  3.19799123e+00   8.46154653e-02   7.89390061e-02]
 [  3.59639903e+00   1.20190232e-01   9.95528978e-02]
 [  3.99393756e+00   1.64418604e-01   1.22417438e-01]
 [  4.39030029e+00   2.18160649e-01   1.47475478e-01]
 [  4.78512184e+00   2.82239403e-01   1.74664385e-01]
 [  5.17797576e+00   3.57435122e-01   2.03916202e-01]
 [  5.56837341e+00   4.44479199e-01   2.35157813e-01]
 [  5.95576394e+00   5.44047900e-01   2.68311131e-01]
 [  6.33953548e+00   6.56755934e-01   3.03293291e-01]
 [  6.71901742e+00   7.83150071e-01   3.4001685

In [49]:
print Car.simulateOneStep()

[  3.99999936e-01   1.66659443e-04   1.24973963e-03]


In [34]:
# Lolz, never use numpy arange

import numpy as np
dt = 0.05
for start in range(0,10):
    t = np.arange(start, start+dt*2.0, dt)
    print t

[ 0.    0.05]
[ 1.    1.05  1.1 ]
[ 2.    2.05  2.1 ]
[ 3.    3.05  3.1 ]
[ 4.    4.05]
[ 5.    5.05]
[ 6.    6.05]
[ 7.    7.05]
[ 8.    8.05]
[ 9.    9.05]


In [38]:
# Always use numpy linspace

import numpy as np
dt = 0.05
for start in range(0,10):
    t = np.linspace(start, start+dt, 2)
    print t



[ 0.    0.05]
[ 1.    1.05]
[ 2.    2.05]
[ 3.    3.05]
[ 4.    4.05]
[ 5.    5.05]
[ 6.    6.05]
[ 7.    7.05]
[ 8.    8.05]
[ 9.    9.05]
